name: Run tests MacOs
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - 0.4.x
concurrency:
  group: macOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-scripted-tests:
    name: Scripted tests
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.17, 3.1.3]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/macos-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Test scripted
        run: |
          LLVM_BIN=$(brew --prefix llvm@14)/bin
          echo $LLVM_BIN
          ls -l $LLVM_BIN
          where llvm-ar

          sbt "test-scripted ${{matrix.scala}}"
