name: Run tests MacOs
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - 0.4.x
concurrency:
  group: macOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-multihreading:
    name: Test experimental multithreading support
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        scala: [3.2.1, 2.13.10]
        build-mode: [debug, release-fast]
        gc: [boehm, immix]
        lto: [thin]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/macos-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Prepare native config command
        shell: bash
        # Following envs CROSS_ are always present in docker container
        run: |
          buildMode=${{matrix.build-mode}}
          if [[ "$buildMode" == "release-fast" ]]; then 
            buildMode=releaseFast
          fi

          SetConfigTemplate=$(cat << EOM
            nativeConfig ~= { prev =>
              prev
                .withMode(scalanative.build.Mode.${buildMode})
                .withGC(scalanative.build.GC.${{matrix.gc}})
                .withLTO(scalanative.build.LTO.${{matrix.lto}})
                .withEmbedResources(true)
                .withCheck(true)
                .withCheckFatalWarnings(true)
                .withMultithreadingSupport(true)
                .withLinkingOptions(prev.linkingOptions ++ Seq("-fuse-ld=lld", "-v"))
            }
          EOM
          )

          echo set-native-config=${SetConfigTemplate} >> $GITHUB_ENV

      - name: Run tests
        env:
          TEST_COMMAND: >
            ++${{matrix.scala}} -v;
            set sandbox.forBinaryVersion("${{env.binary-version}}")/${{env.set-native-config}};
            set tests.forBinaryVersion("${{env.binary-version}}")/${{env.set-native-config}};
            set junitTestOutputsNative.forBinaryVersion("${{env.binary-version}}")/${{env.set-native-config}};
            set scalaPartestJunitTests.forBinaryVersion("${{env.binary-version}}")/${{env.set-native-config}};

            show tests${{env.project-version}}/nativeConfig;

            sandbox${{env.project-version}}/run;
            testsJVM${{env.project-version}}/test;
            tests${{env.project-version}}/test;
            junitTestOutputsJVM${{env.project-version}}/test;
            junitTestOutputsNative${{env.project-version}}/test;
            scalaPartestJunitTests${{env.project-version}}/test
        run: |
          export LLVM_BIN="$(brew --prefix llvm@14)/bin"
          $LLVM_BIN/clang --version
          sbt -J-Xmx5G "${TEST_COMMAND}"
