name: Run tests Linux
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - 0.4.x
concurrency:
  group: linux-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    # This job is basically copy-paste of test-runtime.
  # Scripted tests take a long time to run, ~30 minutes, and should be limited and absolute minimum.
  test-scripted:
    name: Test scripted
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.17, 3.1.3]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Run tests
        env:
          SCALANATIVE_MODE: release-fast
          SCALANATIVE_GC: immix
          SCALANATIVE_OPTIMIZE: true
        run: |
          LLVM_BIN=$(dirname $(readlink -f /usr/bin/clang))
          sbt "test-scripted ${{matrix.scala}}"
