name: Run tests JDK compliance tests
on:
  workflow_call:
  pull_request:
concurrency:
  group: jdk-compliance-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  # Compile and run tests against given version of the JDK to check compliance
  # We test against Java 8 as default in other CI jobs
  tests-unix-jdk-compliance:
    name: Test Unix JDK compliance
    runs-on: ${{matrix.os}}
    env:
      ENABLE_EXPERIMENTAL_COMPILER: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, macos-14]
        scala: [3, 2.13, 3-next]
        java: [21]
        gc: [immix, commix]
        lto: [thin, none]
        exclude:
          - lto: thin
            os: macos-12
          - lto: thin
            os: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/macos-setup-env
        if: ${{ startsWith(matrix.os, 'macos') }}
        with:
          scala-version: ${{matrix.scala}}
          java-version: ${{matrix.java}}
      - uses: ./.github/actions/linux-setup-env
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          scala-version: ${{matrix.scala}}
          java-version: ${{matrix.java}}

      - name: Test runtime
        run: >
          SCALANATIVE_TEST_PREFETCH_DEBUG_INFO=1
          SCALANATIVE_GC=${{matrix.gc}}
          SCALANATIVE_MODE=release-full
          SCALANATIVE_LTO=${{matrix.lto}}
          sbt 
          "-J-Xmx7G" 
          "test-runtime ${{matrix.scala}}"

  tests-windows-jdk-compliance:
    name: Test Windows JDK compliance
    runs-on: windows-2022
    env:
      ENABLE_EXPERIMENTAL_COMPILER: true
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13, 3, 3-next]
        java: [21]
        gc: [immix, commix]
        lto: [thin]
    steps:
      # Disable autocrlf setting, otherwise scalalib patches might not be possible to apply
      - name: Setup git config
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-setup-env
        id: setup
        with:
          scala-version: ${{matrix.scala}}
          java-version: ${{matrix.java}}

      - name: Test runtime
        shell: cmd
        run: >
          set SCALANATIVE_INCLUDE_DIRS=${{steps.setup.outputs.vcpkg-dir}}\include&
          set SCALANATIVE_LIB_DIRS=${{steps.setup.outputs.vcpkg-dir}}\lib&
          set SCALANATIVE_MODE=release-full&
          set SCALANATIVE_GC=${{matrix.gc}}&
          set SCALANATIVE_LTO=${{matrix.lto}}&
          set SCALANATIVE &
          set SCALANATIVE_TEST_PREFETCH_DEBUG_INFO=1 &
          sbt 
          "test-runtime ${{matrix.scala}}"
