name: Run tests JDK compliance tests
on:
  workflow_call:
  pull_request:
concurrency:
  group: jdk-compliance-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  tests-windows-jdk-compliance:
    name: Test Windows JDK compliance
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        scala: [3]
        java: [11, 17, 21]
    steps:
      # Disable autocrlf setting, otherwise scalalib patches might not be possible to apply
      - name: Setup git config
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-setup-env
        id: setup
        with:
          scala-version: ${{matrix.scala}}
          java-version: ${{matrix.java}}

      - name: Test runtime
        shell: cmd
        run: >
          set SCALANATIVE_INCLUDE_DIRS=${{steps.setup.outputs.vcpkg-dir}}\include&
          set SCALANATIVE_LIB_DIRS=${{steps.setup.outputs.vcpkg-dir}}\lib&
          set SCALANATIVE &
          set _JAVA_OPTIONS=${{ matrix.java-options }} &
          set SCALANATIVE_TEST_PREFETCH_DEBUG_INFO=1 &
          sbt 
          "test-runtime ${{matrix.scala}}"
