name: Run tests Windows
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - 0.4.x
concurrency:
  group: windows-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-scripted-tests:
    name: Scripted tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        scala: [2.12.17, 3.1.3]
    steps:
      # Disable autocrlf setting, otherwise scalalib patches might not be possible to apply
      - name: Setup git config
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Test scripted
        run: sbt "++${{matrix.scala}}" "test-scripted ${{matrix.scala}}"
        shell: cmd
