name: Windows tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        scala: [2.13.6, 2.12.15, 2.11.12]
        gc: [none, boehm, immix, commix]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/windows-setup-env
        id: setup
        with:
          scala-version: ${{matrix.scala}}

      - name: Test runtime
        run: >
          set SCALANATIVE_GC=${{matrix.gc}}&
          set SCALANATIVE_INCLUDE_DIRS=${{steps.setup.outputs.vcpkg-dir}}\include&
          set SCALANATIVE_LIB_DIRS=${{steps.setup.outputs.vcpkg-dir}}\lib&
          set SCALANATIVE &
          sbt ++${{matrix.scala}}
          sandbox/run
          testsJVM/test
          tests/test
          testsExt/test
          testsExtJVM/test
        shell: cmd

  run-scripted-tests:
    name: Run scripted tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        scala: [2.12.15]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/windows-setup-env
        with:
          scala-version: ${{matrix.scala}}

      - name: Test scripted
        run: sbt ++${{matrix.scala}};test-scripted
        shell: cmd

  test-runtime-lto:
    name: Test runtime with LTO
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.6, 2.12.15, 2.11.12]
        build-mode: [release-fast]
        lto: [thin]
        optimize: [true]
        include:
          - scala: 2.13.6
            lto: full
            optimize: true
          - scala: 2.12.15
            lto: full
            optimize: false
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/windows-setup-env
        id: setup
        with:
          scala-version: ${{matrix.scala}}

      - name: Test runtime
        run: >
          set SCALANATIVE_GC=immix&
          set SCALANATIVE_MODE=release-fast&
          set SCALANATIVE_OPTIMIZE=${{matrix.optimize}}
          set SCALANATIVE_LTO=${{matrix.lto}}
          set SCALANATIVE_INCLUDE_DIRS=${{steps.setup.outputs.vcpkg-dir}}\include&
          set SCALANATIVE_LIB_DIRS=${{steps.setup.outputs.vcpkg-dir}}\lib&
          set SCALANATIVE &
          sbt ++${{matrix.scala}}
          tests/test
          testsExt/test
        shell: cmd
